version: '3'
services:
  jenkins:
    image: jenkins
    volumes:
    - ./master/:/var/jenkins_home/
    ports:
    - 8080:8080  
  gradle:
    build:
      context: .
      dockerfile: gradle.Dockerfile