node('slave1'){

stage('Git checkout') {
  sh 'rm -rf ./*'
  git branch: 'docker-day-2', url: 'https://github.com/Forbear/docker.git'
  sh 'cp -r docker-2/initial/ ./'
}

stage ('Building docker gradle image'){
	  docker.build ('gradle', '-f docker-2/gradle.Dockerfile .')
}

stage('Building spring-boot app') {
    docker.image('gradle').inside {
      sh 'gradle -b docker-2/initial/build.gradle build'
}
}

stage('Deploying app') {
   sh 'docker-compose up -d'
}

stage('Check') {
  sh 'sleep 5 && curl -LI http://127.0.0.1:8081'
  sh 'docker-compose stop'
}
}